/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CherryCreditInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedServer"
      | "consumeCredit"
      | "credits"
      | "deposit"
      | "distributeReward"
      | "getCredits"
      | "getRewards"
      | "owner"
      | "provenanceExists"
      | "recordProvenance"
      | "rewards"
      | "setAuthorizedServer"
      | "transferOwnership"
      | "verifyProvenance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreditConsumed"
      | "CreditDeposited"
      | "ProvenanceRecorded"
      | "RewardDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedServer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "consumeCredit",
    values: [AddressLike, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "credits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeReward",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "provenanceExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordProvenance",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedServer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProvenance",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consumeCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "credits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCredits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRewards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "provenanceExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordProvenance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProvenance",
    data: BytesLike
  ): Result;
}

export namespace CreditConsumedEvent {
  export type InputTuple = [
    agent: AddressLike,
    amount: BigNumberish,
    conceptId: string,
    actionType: string,
    remainingBalance: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    amount: bigint,
    conceptId: string,
    actionType: string,
    remainingBalance: bigint
  ];
  export interface OutputObject {
    agent: string;
    amount: bigint;
    conceptId: string;
    actionType: string;
    remainingBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditDepositedEvent {
  export type InputTuple = [
    agent: AddressLike,
    amount: BigNumberish,
    newBalance: BigNumberish
  ];
  export type OutputTuple = [agent: string, amount: bigint, newBalance: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProvenanceRecordedEvent {
  export type InputTuple = [
    hash: BytesLike,
    agent: AddressLike,
    conceptId: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    hash: string,
    agent: string,
    conceptId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    hash: string;
    agent: string;
    conceptId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [
    curator: AddressLike,
    amount: BigNumberish,
    conceptId: string
  ];
  export type OutputTuple = [
    curator: string,
    amount: bigint,
    conceptId: string
  ];
  export interface OutputObject {
    curator: string;
    amount: bigint;
    conceptId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CherryCredit extends BaseContract {
  connect(runner?: ContractRunner | null): CherryCredit;
  waitForDeployment(): Promise<this>;

  interface: CherryCreditInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedServer: TypedContractMethod<[], [string], "view">;

  consumeCredit: TypedContractMethod<
    [
      agent: AddressLike,
      amount: BigNumberish,
      conceptId: string,
      actionType: string
    ],
    [void],
    "nonpayable"
  >;

  credits: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  deposit: TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeReward: TypedContractMethod<
    [curator: AddressLike, amount: BigNumberish, conceptId: string],
    [void],
    "nonpayable"
  >;

  getCredits: TypedContractMethod<[agent: AddressLike], [bigint], "view">;

  getRewards: TypedContractMethod<[curator: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  provenanceExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  recordProvenance: TypedContractMethod<
    [hash: BytesLike, agent: AddressLike, conceptId: string],
    [void],
    "nonpayable"
  >;

  rewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setAuthorizedServer: TypedContractMethod<
    [_server: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyProvenance: TypedContractMethod<[hash: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedServer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "consumeCredit"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      amount: BigNumberish,
      conceptId: string,
      actionType: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "credits"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeReward"
  ): TypedContractMethod<
    [curator: AddressLike, amount: BigNumberish, conceptId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCredits"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRewards"
  ): TypedContractMethod<[curator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "provenanceExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordProvenance"
  ): TypedContractMethod<
    [hash: BytesLike, agent: AddressLike, conceptId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAuthorizedServer"
  ): TypedContractMethod<[_server: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyProvenance"
  ): TypedContractMethod<[hash: BytesLike], [boolean], "view">;

  getEvent(
    key: "CreditConsumed"
  ): TypedContractEvent<
    CreditConsumedEvent.InputTuple,
    CreditConsumedEvent.OutputTuple,
    CreditConsumedEvent.OutputObject
  >;
  getEvent(
    key: "CreditDeposited"
  ): TypedContractEvent<
    CreditDepositedEvent.InputTuple,
    CreditDepositedEvent.OutputTuple,
    CreditDepositedEvent.OutputObject
  >;
  getEvent(
    key: "ProvenanceRecorded"
  ): TypedContractEvent<
    ProvenanceRecordedEvent.InputTuple,
    ProvenanceRecordedEvent.OutputTuple,
    ProvenanceRecordedEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;

  filters: {
    "CreditConsumed(address,uint256,string,string,uint256)": TypedContractEvent<
      CreditConsumedEvent.InputTuple,
      CreditConsumedEvent.OutputTuple,
      CreditConsumedEvent.OutputObject
    >;
    CreditConsumed: TypedContractEvent<
      CreditConsumedEvent.InputTuple,
      CreditConsumedEvent.OutputTuple,
      CreditConsumedEvent.OutputObject
    >;

    "CreditDeposited(address,uint256,uint256)": TypedContractEvent<
      CreditDepositedEvent.InputTuple,
      CreditDepositedEvent.OutputTuple,
      CreditDepositedEvent.OutputObject
    >;
    CreditDeposited: TypedContractEvent<
      CreditDepositedEvent.InputTuple,
      CreditDepositedEvent.OutputTuple,
      CreditDepositedEvent.OutputObject
    >;

    "ProvenanceRecorded(bytes32,address,string,uint256)": TypedContractEvent<
      ProvenanceRecordedEvent.InputTuple,
      ProvenanceRecordedEvent.OutputTuple,
      ProvenanceRecordedEvent.OutputObject
    >;
    ProvenanceRecorded: TypedContractEvent<
      ProvenanceRecordedEvent.InputTuple,
      ProvenanceRecordedEvent.OutputTuple,
      ProvenanceRecordedEvent.OutputObject
    >;

    "RewardDistributed(address,uint256,string)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
  };
}
