/* Advanced 페이지 콘텐츠 — 1/2 (Advanced Prompting · Multi-hop RAG · PEFT)
   기획: apps/docs/advanced/2-implementation-guide.md §5

   규칙 (1-work-guidelines.md §2 · V5)
     · 체리는 원문 **전문**을 읽고 쓴다. 앞부분만 보고 요약하지 않는다.
     · axis 는 서로 겹치지 않아야 한다(MECE). Overview 의 ③ "일의 모양"을 덮는다.
     · insight 가 원문이 말하지 않은 것을 말하면 안 된다.
     · 수치에는 측정 조건을 붙인다.
     · References 는 4단계. 소장 도서는 책·장을 정확히, 외부는 실제 열리는 URL. */

module.exports = [
{
  node: "AdvancedPrompting",
  title: "Advanced Prompting",
  section: "BASICS_OR_ADVANCED_PLACEHOLDER",
  overview: [
    "Advanced prompting is what you do once a clear instruction is no longer enough. Instead of only telling the model *what* you want, you shape *how* it gets there — what examples it sees, what role it holds, how much of the reasoning it writes down, and how many times it is allowed to try. None of it touches the weights.",
    "**Why it matters:** this is the cheapest adaptation available. A prompt change takes effect immediately, costs nothing to train, and is scoped to the session you are in. When a model fails on a task, prompting is the first lever to pull, and often the only one you need.",
    "**The shape of the work:** put examples in the context, split the system instruction from the user turn, let the model write out intermediate steps, generate several attempts and reconcile them, and have the model criticise its own output. The Prompt Report groups the published techniques into five families — in-context learning, thought generation, decomposition, ensembling, and self-criticism.",
  ].join("\n\n"),
  cherries: [
    { axis: "Learning without training",
      chunk: "019e785e-8a41-705d-b51d-cbee2127dc95", primary: true,
      insight: "In-context learning was named in the GPT-3 paper (Brown et al., 2020). Its claim is narrow and strange: a model trained only for next-token prediction learned translation, reading comprehension and SAT questions from examples placed in the prompt, with no weight update. Everything called advanced prompting rests on that observation." },
    { axis: "How much fiddling a model needs is a property of the model",
      chunk: "019e785e-8a3a-74fd-bff3-38abb57fa1dc",
      insight: "Write \"5\" instead of \"five\", add a newline, change capitalisation — a fragile model answers differently. You can measure this by randomly perturbing prompts and watching the output move. Robustness tracks overall capability, so stronger models need less prompt engineering. Prompting effort is partly a symptom of model choice." },
    { axis: "Separating the standing instruction from the turn",
      chunk: "019e785e-8a3a-7d28-9b9f-38e17aaf7dce",
      insight: "The system prompt holds what stays true across the whole conversation — the role, the standard of care, the output style. The user prompt holds what changes: this question, this document. Splitting them is what makes a roleplaying instruction survive a long session instead of being restated and slowly drifting." },
    { axis: "Letting a model write the prompt",
      chunk: "019e785e-8a21-7b33-ba36-cc2fc889964f",
      insight: "Prompt optimisation is now automated. DeepMind's Promptbreeder (2023) treats prompts as a population: an AI generates mutations of a starting prompt, guided by mutator prompts, then mutates the most promising ones again. Stanford's TextGrad (2024) takes a different route to the same end. Hand-tuning is no longer the only option." },
    { axis: "The change that takes effect immediately",
      chunk: "019e785e-8a20-76d5-9bd5-03b005e5e981",
      insight: "When an agent keeps failing on one kind of error, adding a worked example to the prompt fixes it instantly and only for that session — no retraining, no deployment. The same channel absorbs user corrections mid-conversation. That immediacy is the whole argument for prompting over fine-tuning as a first response." },
  ],
  references: [
    { order: 1, stage: "START HERE", title: 'AI Engineering — Ch.5 "Prompt Engineering"', url: null, inLibrary: true, byline: "Chip Huyen",
      teaches: "What a prompt is made of — in-context learning, system versus user prompt, context efficiency — and how much of it you actually need.",
      addsOverPrevious: "the foundation" },
    { order: 2, stage: "NEXT →", title: "The Prompt Report: A Systematic Survey of Prompting Techniques", url: "https://arxiv.org/abs/2406.06608", inLibrary: false, byline: "Schulhoff et al., 2024",
      teaches: "A taxonomy of 58 text prompting techniques in five families, built from 1,565 papers — the map of what has actually been tried.",
      addsOverPrevious: "breadth, and standard names for things" },
    { order: 3, stage: "THEN →", title: 'Building Applications with AI Agents — Ch.11 "Improvement Loops"', url: null, inLibrary: true, byline: "Michael Albada",
      teaches: "Prompting as an operational loop: refining prompts from observed failures, and where in-context learning sits next to retraining.",
      addsOverPrevious: "what happens after the first prompt ships" },
    { order: 4, stage: "DEEP DIVE →", title: "Towards Better Chain-of-Thought Prompting Strategies: A Survey", url: "https://arxiv.org/pdf/2310.04959", inLibrary: false, byline: null,
      teaches: "Where chain-of-thought helps, where it does not, and which design choices in a CoT prompt actually move the result.",
      addsOverPrevious: "the limits of the most famous technique" },
  ],
},
{
  node: "MultiHopRAG",
  title: "Multi-hop RAG",
  overview: [
    "Multi-hop RAG handles questions a single retrieval cannot answer. The result of one search becomes the input to the next: find the author, then find their institution, then find who leads it. The retrieval loop and the reasoning loop are interleaved rather than run once.",
    "**Why it matters:** baseline RAG chunks documents, embeds them, and returns the chunks nearest the question. That works for direct lookup and fails whenever the answer has to be assembled from pieces scattered across documents, or summarised across a whole corpus.",
    "**The shape of the work:** rewrite or expand the question, pull structured constraints out of it, decide where to look next, and — the part everyone underestimates — decide when to stop. Retrieve too long and cost explodes; stop too early and the answer is confidently wrong.",
  ].join("\n\n"),
  cherries: [
    { axis: "Where single-shot retrieval breaks",
      chunk: "019e785e-8a26-703f-8cc0-55fb01a24776", primary: true,
      insight: "Baseline RAG fails on three shapes of question: answers that require connecting information scattered across documents, queries that ask for themes across a dataset, and corpora that are large, messy or narrative rather than a list of facts. \"What has Geoffrey Hinton done?\" has no single chunk that answers it. Building a graph of entities and relationships is what makes multihop reasoning possible." },
    { axis: "Asking the same question several ways",
      chunk: "019e785e-8a3d-7f93-9c21-59d9138835a6",
      insight: "Query expansion generates N rewrites of the user's question and retrieves for each. The stated purpose is to work around a limitation of the retriever itself — distance-based similarity search sees one phrasing, and one phrasing may sit far from the passage that holds the answer." },
    { axis: "Pulling structure out of a sentence",
      chunk: "019e785e-8a3e-7ea2-8f7d-42c3198b7586",
      insight: "Self-querying extracts the filterable parts of a question — a user name, an id — before search runs, so they become metadata filters rather than words in an embedding. It is the recognition that part of a question is a constraint, not a topic." },
    { axis: "Semantically close, contextually wrong",
      chunk: "019e785e-8a3f-7d84-89d3-5c044b73e031",
      insight: "Plain vector search retrieves documents that share language patterns but miss the intent. Search for \"Java\" and you get the programming language or the Indonesian island, because embeddings capture general semantic meaning and nothing about which one you meant. Filtering exists because similarity alone underdetermines relevance." },
    { axis: "Does a bigger context window end all this?",
      chunk: "019e785e-8a21-716a-a301-bab066fc5a65",
      insight: "Feeding millions of tokens in one shot removes the retrieval machinery and adds compute, latency and cost — and no guarantee the model finds the one relevant line in that window. The book's position is hedged on purpose: larger contexts may make elaborate search obsolete, but for now hybrid systems win on fact-seeking queries, freshness and precision ranking." },
  ],
  references: [
    { order: 1, stage: "START HERE", title: 'AI Engineering — Ch.6 "RAG and Agents"', url: null, inLibrary: true, byline: "Chip Huyen",
      teaches: "The retrieval-first mental model, and why chunking and reranking decide output quality more than model choice does.",
      addsOverPrevious: "the foundation" },
    { order: 2, stage: "NEXT →", title: 'LLM Engineers Handbook — Ch.9 "RAG Inference Pipeline"', url: null, inLibrary: true, byline: null,
      teaches: "Query expansion, self-querying and filtered vector search as running code — the pieces a multi-hop loop is built from.",
      addsOverPrevious: "implementation" },
    { order: 3, stage: "THEN →", title: "Retrieval–Reasoning Processes for Multi-hop QA: A Four-Axis Design Framework", url: "https://arxiv.org/html/2601.00536v1", inLibrary: false, byline: null,
      teaches: "Four axes that separate every published multi-hop system: execution plan, index structure, next-step control, and stopping criterion.",
      addsOverPrevious: "the design space, named" },
    { order: 4, stage: "DEEP DIVE →", title: "Agentic Retrieval-Augmented Generation: A Survey", url: "https://arxiv.org/html/2501.09136v4", inLibrary: false, byline: null,
      teaches: "What changes when the agent, not the pipeline, decides how many times to retrieve.",
      addsOverPrevious: "where the control moves next" },
  ],
},
{
  node: "ParameterEfficientFinetuning",
  title: "PEFT / LoRA / QLoRA",
  overview: [
    "Parameter-efficient fine-tuning adapts a large model by training a small set of new or selected parameters while the original weights stay frozen. One base model can then serve many tasks, because what you ship per task is a few megabytes rather than a new copy of the model.",
    "**Why it matters:** the memory arithmetic of full fine-tuning rules it out on ordinary hardware. PEFT is what puts adaptation back within reach of a single GPU, and it is why swapping behaviour per customer or per task is an operational decision rather than a capital one.",
    "**The shape of the work:** add small trainable modules (adapters, soft prompts), select a subset of existing parameters, or re-express the update in low rank (LoRA) — optionally on top of a quantised base (QLoRA). Then decide what you gave up relative to full fine-tuning, and whether fine-tuning was the right tool at all.",
  ].join("\n\n"),
  cherries: [
    { axis: "The number that rules out full fine-tuning",
      chunk: "019e785e-8a27-7e49-b9c8-6e40ce5a1bf3", primary: true,
      insight: "A 7B model in FP16 needs 14 GB just to hold the weights. Full fine-tuning with Adam adds gradients and optimizer states — 7B × 3 × 2 bytes = 42 GB — for 56 GB before activations are counted. Consumer GPUs carry 12–24 GB. That gap, not elegance, is why parameter-efficient methods exist." },
    { axis: "Freezing most layers is not enough",
      chunk: "019e785e-8a3a-7748-8cec-0a94fbb69784",
      insight: "Partial fine-tuning cuts memory but is parameter-inefficient: Houlsby et al. (2019) found that BERT-large needed roughly 25% of its parameters updated to approach full fine-tuning on GLUE. Training fewer layers is not the same as training fewer parameters well — which is the gap the LoRA family targets." },
    { axis: "Going below 16 bits",
      chunk: "019e785e-8a24-74f7-bf69-ad0c462efc7a",
      insight: "Serving moved from FP32 to 16-bit and lower: LLM.int8() at 8 bits and QLoRA at 4 bits (Dettmers et al., 2022, 2023), Apple shipping a 2-bit/4-bit mixture averaging 3.5 bits per weight in 2024, NVIDIA's Blackwell adding 4-bit float inference. Below 8 bits the representation itself gets awkward — minifloats like FP8/FP4, or integer formats such as INT8/INT4." },
    { axis: "Combining models instead of retraining one",
      chunk: "019e785e-8a32-78ad-99cf-b9707377eef1",
      insight: "Model merging aims for a single model worth more than its parts: if one model answers the first 60% of questions and another the last 60%, the merge might answer 80%. It is an alternative to multi-task fine-tuning that costs no training run at all." },
    { axis: "A use case people forget",
      chunk: "019e785e-8a3d-7351-9e26-131e456cc930",
      insight: "Fine-tuning is also a bias-mitigation tool. If a base model keeps giving CEOs male names, fine-tuning on a dataset with many female CEOs pushes back. Garimella et al. (2022) reduced gender bias in BERT-like models by fine-tuning on text authored by women, and racial bias by fine-tuning on African authors — adaptation aimed at the model's defaults rather than at a task." },
  ],
  references: [
    { order: 1, stage: "START HERE", title: 'AI Engineering — Ch.7 "Finetuning"', url: null, inLibrary: true, byline: "Chip Huyen",
      teaches: "When to fine-tune and when not to, the memory arithmetic behind the decision, and where PEFT and quantization fit.",
      addsOverPrevious: "the foundation" },
    { order: 2, stage: "NEXT →", title: 'LLM Engineers Handbook — Ch.5 "Supervised Fine-Tuning"', url: null, inLibrary: true, byline: null,
      teaches: "Fine-tuning as a pipeline — data filtering, deduplication, decontamination, batch size, packing, optimizers.",
      addsOverPrevious: "the part that is data work, not model work" },
    { order: 3, stage: "THEN →", title: "LoRA: Low-Rank Adaptation of Large Language Models", url: "https://arxiv.org/abs/2106.09685", inLibrary: false, byline: "Hu et al., 2021",
      teaches: "The method itself: freeze the weights, learn two low-rank matrices. Reports 10,000x fewer trainable parameters and 3x less GPU memory on GPT-3 175B.",
      addsOverPrevious: "the primary source" },
    { order: 4, stage: "DEEP DIVE →", title: "Parameter-Efficient Fine-Tuning for Large Models: A Comprehensive Survey", url: "https://arxiv.org/html/2403.14608v6", inLibrary: false, byline: null,
      teaches: "The full landscape in four families — additive, selective, reparameterized, hybrid — with roughly sixty named methods placed in it.",
      addsOverPrevious: "everything LoRA is not" },
  ],
},
];
