/* 교체된 개념 + Basics 의 Embedding — 페이지 콘텐츠
   메뉴에서 교체됐어도 '링크 타고 들어가는 페이지'로 남는다. 조사한 재료가 있으니 채운다.
   ⚠️ 이미 다른 개념의 체리로 쓴 문단은 재사용하지 않는다(같은 문장이 두 페이지에 뜨지 않게). */
module.exports = [
{
  node: "Embedding", title: "Embeddings", section: "BASICS",
  overview: [
    "An embedding is a piece of text — or an image — turned into a list of numbers positioned so that things which mean similar things sit near each other. Everything downstream of retrieval depends on that geometry being right.",
    "**Why it matters:** it is what lets a system find a passage that answers a question without sharing a single word with it. Keyword search cannot do that, and no amount of prompt work compensates for a retriever that never surfaces the right text.",
    "**The shape of the work:** pick a model, decide how to cut documents into chunks, store the vectors somewhere that can search them quickly, and measure similarity — usually by cosine distance. Each of those four choices moves retrieval quality.",
  ].join("\n\n"),
  cherries: [
    { axis: "What an embedding is, and where it came from",
      chunk: "019e785e-8a3e-7c27-aeed-7c66ad48b2d1", primary: true,
      insight: "Embeddings are vector representations that capture meaning from how words are used across large corpora — Word2Vec, GloVe and BERT placed semantically similar words near each other in a high-dimensional space, and LLM-scale training extended that across far more kinds of text. The payoff is stated precisely: retrieving relevant information across documents that share no exact keywords." },
    { axis: "Reading a similarity score",
      chunk: "019e785e-8a2d-7106-9003-12e0764f24c6",
      insight: "The worked example is the fastest way to build intuition: a sentence compared with itself scores 1, a sentence with nothing in common scores near 0, and partial overlap lands in between. Cosine similarity is not a probability and not a percentage — it is a position on that scale." },
    { axis: "Where the vectors live",
      chunk: "019e785e-8a3f-7727-b7f4-796fe88661a2",
      insight: "Vector stores — FAISS, Annoy, and the managed equivalents — exist because similarity search over high-dimensional vectors is not something an ordinary database does quickly. The agent embeds its query, asks the store for the nearest stored vectors, and gets back the memory that matches in meaning rather than in wording." },
    { axis: "Nearest, not exact",
      chunk: "019e785e-8a2e-7b8f-a855-1e798c9a6ade",
      insight: "A traditional database returns exact matches. A vector database returns closest neighbours, computed with approximate nearest neighbour algorithms — approximate being the operative word. The result set is a ranked guess, which is why everything downstream is built to tolerate and re-rank it." },
    { axis: "An index is not a database",
      chunk: "019e785e-8a30-7cce-a58f-2fd3bc7a9f10",
      insight: "A standalone vector index such as FAISS does similarity search well and stops there. Vector databases add CRUD, metadata filtering, scalability, real-time updates, backups and security — the operational surface that decides whether the thing survives production, none of which is about search quality." },
  ],
  references: [
    { order: 1, stage: "START HERE", title: "Chunking", url: null, internalNode: "Chunking", inLibrary: true, byline: null,
      teaches: "How documents are cut before they are embedded — the choice that decides what a vector can represent.",
      addsOverPrevious: "the step before" },
    { order: 2, stage: "NEXT →", title: "Vector Databases", url: null, internalNode: "VectorDatabase", inLibrary: true, byline: null,
      teaches: "Where embeddings are stored and how nearest-neighbour search actually runs.",
      addsOverPrevious: "the step after" },
    { order: 3, stage: "THEN →", title: "Recent Advances in Text Embedding: A Review of Top-Performing Methods on MTEB", url: "https://arxiv.org/html/2406.01607v1", inLibrary: false, byline: null,
      teaches: "How the leading models are actually trained, and the 8 tasks MTEB scores them on.", addsOverPrevious: "how to choose a model on evidence" },
    { order: 4, stage: "DEEP DIVE →", title: "Matryoshka Representation Learning", url: "https://arxiv.org/abs/2205.13147", inLibrary: false, byline: "Kusupati et al., 2022",
      teaches: "One embedding you can truncate: 14x smaller vectors at comparable ImageNet-1K accuracy. (Vision result — do not carry the number straight to text.)",
      addsOverPrevious: "the cost dimension nobody mentions first" },
  ],
},
{
  node: "HybridRetrieval", title: "Hybrid Retrieval", section: null,
  overview: [
    "Hybrid retrieval runs keyword search and vector search over the same corpus and merges the two ranked lists, usually with a weight — commonly called alpha — deciding how much each side counts.",
    "**Why it matters:** the two methods fail in opposite directions. Vector search finds passages that mean the same thing and stumbles on exact strings; keyword search nails the exact string and misses every paraphrase. Most real queries contain some of both.",
    "**The shape of the work:** index twice, search twice, normalise two incomparable score scales, and merge. Then decide whether the query needed the blend at all, because the alpha that helps one query hurts another.",
  ].join("\n\n"),
  cherries: [
    { axis: "The two levers you actually have",
      chunk: "019e785e-8a2a-75e2-9987-4c7fc7657842", primary: true,
      insight: "Retrieval improves along exactly two paths: change the embedding model that encodes chunks and queries, or use the database's own filter and search features. The first is a training problem, the second an infrastructure one — and hybrid retrieval is the second path taken seriously." },
    { axis: "How the keyword half ranks",
      chunk: "019e785e-8a42-7055-b6b1-b1c6596dadea",
      insight: "The keyword side is usually BM25, which weighs term frequency, inverse document frequency and document length — so rare words count more and long passages are not rewarded for containing everything. The query is analysed with the same pipeline used for indexing, which is why a mismatch between the two silently ruins recall." },
    { axis: "Fixing the query before it reaches the index",
      chunk: "019e785e-8a42-7e00-a294-967ece1da859",
      insight: "Pre-retrieval rewriting reshapes the question to match how the data is stored — paraphrasing, substituting synonyms, splitting long questions into sub-queries, or HyDE, where an LLM writes a hypothetical answer and both the question and that answer go to the retriever. All of it is compensation for the gap between how people ask and how documents are written." },
  ],
  references: [
    { order: 1, stage: "START HERE", title: "Sparse Retrieval", url: null, internalNode: "SparseRetrieval", inLibrary: true, byline: null,
      teaches: "The keyword half — exact term matching and BM25 ranking.",
      addsOverPrevious: "one of the two halves" },
    { order: 2, stage: "NEXT →", title: "Dense Retrieval", url: null, internalNode: "DenseRetrieval", inLibrary: true, byline: null,
      teaches: "The vector half — semantic similarity and its blind spot for exact strings.",
      addsOverPrevious: "the other half" },
    { order: 3, stage: "THEN →", title: "Retrieval–Reasoning Processes for Multi-hop QA: A Four-Axis Design Framework", url: "https://arxiv.org/html/2601.00536v1", inLibrary: false, byline: null,
      teaches: "Where ranking sits relative to index structure and execution plan — hybrid retrieval is one axis, not the whole design.", addsOverPrevious: "the surrounding design space" },
    { order: 4, stage: "DEEP DIVE →", title: "NV-Retriever: Improving text embedding models with effective hard-negative mining", url: "https://arxiv.org/html/2407.15831v1", inLibrary: false, byline: "NVIDIA, 2024",
      teaches: "The other lever — improving the dense side itself, and why the negatives chosen during training decide how good it can get.", addsOverPrevious: "fixing the half you were compensating for" },
  ],
},
{
  node: "MultiAgentSystem", title: "Multi-agent Systems", section: null,
  overview: [
    "A multi-agent system is a set of agents that interact to reach a goal no single one of them handles well. It is the structure — who exists, what each can do, who may talk to whom — as distinct from the control layer that runs it.",
    "**Why it matters:** one agent with every tool degrades as its toolset grows; it picks the wrong tool more often. Splitting the work narrows each agent's decisions. What you buy in reliability you pay for in coordination.",
    "**The shape of the work:** decide the specialists, decide who talks to whom, and accept the bill — communication overhead, synchronisation, and conflicts when two agents want the same resource or pursue overlapping goals.",
  ].join("\n\n"),
  cherries: [
    { axis: "The bill that comes with more agents",
      chunk: "019e785e-8a3e-7685-a664-ea984058faab", primary: true,
      insight: "The costs are named plainly: coordination complexity rises with every interacting agent, communication overhead slows the system and consumes resources at scale, and agents with overlapping goals conflict unless there are protocols for resolution and resource allocation. None of this appears in a two-agent demo." },
    { axis: "What the structure buys you when something fails",
      chunk: "019e785e-8a27-7059-9c77-f6a9ddeb0520",
      insight: "Because routing is decided at runtime rather than by a fixed path, the system can reroute on live signals — a weather event, a market shift — and can fork to several specialists at once. The resilience argument follows from the same property: one agent going down with an API outage does not halt the process." },
    { axis: "Letting agents talk through a bus instead of directly",
      chunk: "019e785e-8a2a-708e-ba43-b2992b928f98",
      insight: "In the message-broker pattern each specialist consumes from a stream, does its work, and publishes to a response stream. Nobody calls anybody. Agents can be added, restarted or scaled without rewiring the others — the decoupling that direct calls between agents give up." },
  ],
  references: [
    { order: 1, stage: "START HERE", title: "Agents", url: null, internalNode: "AgentArchitecture", inLibrary: true, byline: null,
      teaches: "What one agent is made of, before you have several.",
      addsOverPrevious: "the ground you build on" },
    { order: 2, stage: "NEXT →", title: "The Orchestration of Multi-Agent Systems: Architectures, Protocols, and Enterprise Adoption", url: "https://arxiv.org/abs/2601.13671", inLibrary: false, byline: null,
      teaches: "The control layer treated separately from the agents — planning, policy, state, quality.", addsOverPrevious: "how the structure gets run" },
    { order: 3, stage: "THEN →", title: "Multi-Agent Collaboration Mechanisms: A Survey of LLMs", url: "https://arxiv.org/abs/2501.06322", inLibrary: false, byline: "Tran et al., 2025",
      teaches: "Five axes for describing any collaboration — actors, types, structures, strategies, protocols — including competition and coopetition, not just cooperation.",
      addsOverPrevious: "vocabulary for comparing systems" },
    { order: 4, stage: "DEEP DIVE →", title: "A Taxonomy of Hierarchical Multi-Agent Systems", url: "https://arxiv.org/abs/2508.12683", inLibrary: false, byline: null,
      teaches: "Control, information flow, delegation, temporal layering and communication structure as five separate design dimensions.",
      addsOverPrevious: "what 'hierarchical' actually decomposes into" },
  ],
},
{
  node: "RedTeaming", title: "Red Teaming", section: null,
  overview: [
    "Red teaming is the search for the inputs nobody planned for. A team — human, automated, or both — attacks the system on purpose to find failure modes that ordinary testing never reaches.",
    "**Why it matters:** it is the discovery half of safety work. A benchmark can only score the attacks it already contains; something has to find the next one. That is a different activity from measuring, with a different output — a list of vulnerabilities rather than a number.",
    "**The shape of the work:** formulate what counts as failure, pick strategies, execute, document what you found, and fix it. Then repeat, because the threat model moves.",
  ].join("\n\n"),
  cherries: [
    { axis: "Talking a model out of its own rules",
      chunk: "019e785e-8a39-73e9-8eac-387dd763d667", primary: true,
      insight: "The DAN prompt is the archetype of jailbreaking: assign the model a persona defined as having no restrictions, assert that the persona can do anything, and add a correction mechanism for when it slips back into character. The attack carries no exploit — it is entirely an argument about who the model is." },
    { axis: "Hiding instructions inside data",
      chunk: "019e785e-8a22-7d3f-98bc-4896542b8239",
      insight: "JSON-based prompt injection dresses malicious instructions as system logs, configuration, or trusted internal messages, exploiting the fact that models treat structured input as authoritative. The example asks for a French translation and embeds a directive that overrides it — the payload arrives in the position the application reserved for data." },
    { axis: "What separates it from testing",
      chunk: "019e785e-8a3d-7b6e-9a0f-1353d2bb871d",
      insight: "Ordinary software testing asks whether the system does what it should. Red teaming asks how it behaves under intentional misuse, adversarial manipulation and edge cases. The book ties the need to a property of the models themselves — probabilistic, and vulnerable to subtle prompt manipulation — which is why functional correctness tests do not cover it." },
    { axis: "Nobody can say how well-guarded a system is",
      chunk: "019e785e-8a20-7b9c-930f-6f7620d70428",
      insight: "Injection benchmarks score detection accuracy across systems and the spread is wide — Lakera Guard at 92.5% against Llama Prompt Guard at 61.4% on the PINT Score. The conclusion drawn is not a ranking but an admission: the field is early enough that how well-guarded a system truly is remains hard to establish, which is the argument for continuous testing rather than a certificate." },
  ],
  references: [
    { order: 1, stage: "START HERE", title: "Jailbreak", url: null, internalNode: "Jailbreak", inLibrary: true, byline: null,
      teaches: "The attack that talks a model out of its own refusal rules.",
      addsOverPrevious: "one attack family, in depth" },
    { order: 2, stage: "NEXT →", title: "Adversarial Evaluation", url: null, internalNode: "AdversarialEvaluation", inLibrary: true, byline: null,
      teaches: "The measuring half — turning what you found into a repeatable score.",
      addsOverPrevious: "the other half of the pair" },
    { order: 3, stage: "THEN →", title: "HarmBench: A Standardized Evaluation Framework for Automated Red Teaming", url: "https://arxiv.org/html/2402.04249v2", inLibrary: false, byline: "Mazeika et al., 2024",
      teaches: "18 automated red teaming methods compared against 33 models — and the finding that within model families robustness does not track size.",
      addsOverPrevious: "what the methods score when compared fairly" },
    { order: 4, stage: "DEEP DIVE →", title: "Red Teaming AI Red Teaming", url: "https://arxiv.org/html/2507.05538v2", inLibrary: false, byline: null,
      teaches: "The critique: model-level focus, no agreed scope, testing after the system is built — and why red teaming complements formal testing rather than replacing it.",
      addsOverPrevious: "it questions the practice the first three teach" },
  ],
},
{
  node: "RAG", title: "RAG", section: "BASICS",
  /* ⚠️ 이 페이지는 2026-08-19 에 먼저 만들어져 References 가 "책 N장" 형식이었다.
     챕터 리더 화면이 없어 갈 데가 없었으므로, 다른 페이지와 같은 규칙으로 맞춘다.
     Overview 와 체리 7건은 그대로 둔다(이미 발행된 유일한 검증 대상). */
  keepOverview: true, keepCherries: true,
  references: [
    { order: 1, stage: "START HERE", title: "Embeddings", url: null, internalNode: "Embedding", inLibrary: true, byline: null,
      teaches: "What a vector is and how similarity is measured — retrieval quality is capped here.", addsOverPrevious: "the ground you build on" },
    { order: 2, stage: "NEXT →", title: "Chunking", url: null, internalNode: "Chunking", inLibrary: true, byline: null,
      teaches: "How documents are cut before indexing, and why the unit convenient for the model is not the unit that carries meaning.", addsOverPrevious: "the step that decides what can be retrieved" },
    { order: 3, stage: "THEN →", title: 'Anthropic — "Introducing Contextual Retrieval" (2024)', url: "https://www.anthropic.com/news/contextual-retrieval", inLibrary: false, byline: null,
      teaches: "Prepending a short situating description to each chunk before indexing, so a passage carries its own context.", addsOverPrevious: "a concrete fix for the failure the first two only name" },
    { order: 4, stage: "DEEP DIVE →", title: "Multi-hop RAG", url: null, internalNode: "MultiHopRAG", inLibrary: true, byline: null,
      teaches: "What happens when one retrieval is not enough and the loop has to run again.", addsOverPrevious: "where single-shot RAG stops working" },
  ],
},
];
