/* Advanced 페이지 콘텐츠 — 2/2 (Multi-agent Orchestration · Custom Embeddings · Adversarial Evaluation)
   규칙은 content-1.cjs 머리말과 같다. */
module.exports = [
{
  node: "MultiAgentOrchestration",
  title: "Multi-agent Orchestration",
  overview: [
    "Multi-agent orchestration is the control layer above a set of agents. It decides which agent acts, when, on what shared state, and with what authority — planning, policy, state and quality operations. The agents are the workforce; orchestration is the management.",
    "**Why it matters:** one agent holding every tool makes worse choices as its toolset grows. Splitting the work into specialists narrows each prompt and each tool list, which reduces selection errors — but every agent you add brings communication overhead, coordination complexity and new ways to fail.",
    "**The shape of the work:** pick a coordination model (a manager, a peer group, or a hierarchy), decide how agents talk (shared state, messages, or handoffs), and put the whole thing on something that survives a crash. The failure modes are specific to this layer: loops that never terminate, cost that grows with every hand-off, and state two agents disagree about.",
  ].join("\n\n"),
  cherries: [
    { axis: "Why splitting helps at all",
      chunk: "019e785e-8a3a-7fff-b84b-b61ffe32bf64", primary: true,
      insight: "The worked example decomposes sixteen tools into three specialists — inventory, transportation, supplier compliance — with a supervisor routing to them. The stated benefit is not parallelism but specialisation: narrowing each agent's toolset and prompt reduces selection errors and improves reliability." },
    { axis: "The cost of every agent you add",
      chunk: "019e785e-8a28-7541-976c-56a626fe5231",
      insight: "Parsimony is the principle of adding only the minimum number of agents that does the job. Each addition brings communication overhead, coordination complexity and resource demand. The test the book proposes is concrete: before adding an agent, ask whether an existing agent could take the responsibility, or whether an existing capability could be extended." },
    { axis: "A manager decides",
      chunk: "019e785e-8a25-79f9-a955-4fc3c3e37ffd",
      insight: "Manager coordination designates one or more agents to direct the rest. Decisions are made on the group's behalf, which skips the negotiation a peer system needs, keeps task assignment unambiguous, and simplifies communication — subordinates talk to their manager rather than to everyone." },
    { axis: "Or nobody decides",
      chunk: "019e785e-8a41-7e9d-8e35-5f46d9946659",
      insight: "Democratic coordination gives every agent equal say and no leader. Its strength is the absence of a single point of failure: the system keeps working when individual agents fail. The cost is the negotiation that manager coordination avoids — the same trade-off, seen from the other side." },
    { axis: "Or both, in layers",
      chunk: "019e785e-8a3a-7f8b-b43a-b7b10d42b474",
      insight: "Hierarchical coordination stacks the two: higher-level agents direct lower ones while leaving them some autonomy. Coordination work spreads across levels instead of concentrating in one manager, which is what lets the agent count grow; layering also adds redundancy, since a task can be handled at more than one level." },
    { axis: "Making it survive a crash",
      chunk: "019e785e-8a22-7e35-afae-5958f0a48ba5",
      insight: "Workflow engines sit above the agents and separate coordination logic from communication mechanics. What they buy you is idempotency, recoverability and durable state — properties that stop mattering in a demo and start mattering the first time an agent stalls or an API goes down mid-run." },
    { axis: "Letting the system design itself",
      chunk: "019e785e-8a32-759d-ba2b-6b5c2033ad74",
      insight: "ADAS (Hu, Lu and Clune, 2024) proposes that a Meta Agent Search algorithm create, evaluate and refine agentic systems instead of engineers hand-building each component. The argument by analogy is that hand-designed solutions in machine learning have repeatedly been replaced by learned ones." },
  ],
  references: [
    { order: 1, stage: "START HERE", title: 'Building Applications with AI Agents — Ch.8 "From One Agent to Many"', url: null, inLibrary: true, byline: "Michael Albada",
      teaches: "Coordination models side by side — manager, democratic, hierarchical, swarm — with the trade-off each one makes.",
      addsOverPrevious: "the foundation" },
    { order: 2, stage: "NEXT →", title: 'Building Applications with AI Agents — Ch.5 "Orchestration"', url: null, inLibrary: true, byline: "Michael Albada",
      teaches: "Graphs and context engineering as the mechanics underneath a coordination model.",
      addsOverPrevious: "how the control flow is actually expressed" },
    { order: 3, stage: "THEN →", title: "A Survey of Agent Interoperability Protocols: MCP, ACP, A2A, ANP", url: "https://arxiv.org/html/2505.02279v1", inLibrary: false, byline: null,
      teaches: "The four protocols agents use to find and call each other, and a staged order for adopting them.",
      addsOverPrevious: "what happens once the agents are not yours" },
    { order: 4, stage: "DEEP DIVE →", title: "The Orchestration of Multi-Agent Systems: Architectures, Protocols, and Enterprise Adoption", url: "https://arxiv.org/abs/2601.13671", inLibrary: false, byline: null,
      teaches: "Orchestration treated as its own layer — planning, policy enforcement, state management, quality operations — rather than as a property of the agents.",
      addsOverPrevious: "the concept this page is named after, defined formally" },
  ],
},
{
  node: "CustomEmbedding",
  title: "Custom Embeddings",
  overview: [
    "Custom embeddings are what you get when you stop using a general-purpose embedding model as-is and adapt it to your domain. General models handle everyday language well and miss the distinctions that decide relevance inside law, medicine, or one company's documents.",
    "**Why it matters:** retrieval quality is capped by the embedding. No amount of reranking rescues a retriever that never surfaces the right passage, and the gap between a generic and an adapted model is largest exactly where the vocabulary is narrow and the stakes are high.",
    "**The shape of the work:** pick a starting model deliberately, train it contrastively on pairs from your own data, choose the wrong answers you train against with care, and decide how much vector you actually need to store. Which negatives you pick matters more than almost anything else in the pipeline.",
  ].join("\n\n"),
  cherries: [
    { axis: "The starting model is a decision, not a default",
      chunk: "019e785e-8a2b-78df-a5da-af51d2db7837", primary: true,
      insight: "The best embedding model changes over time and with the use case. The book points at MTEB on Hugging Face and names three different ways to read the leaderboard — best overall, best accuracy, smallest memory footprint — and says the choice follows from your requirements, not from the ranking." },
    { axis: "Putting different kinds of data in one space",
      chunk: "019e785e-8a34-7d60-a8fa-5fef843227f5",
      insight: "Comparing a sentence to an image requires a model built for it. Specialised models such as CLIP project both types into the same vector space; without that shared space the distance between two embeddings is not a meaningful number, however confidently it computes." },
    { axis: "The accurate model you cannot afford to run first",
      chunk: "019e785e-8a34-7275-8b7a-7b3f1c32b2fb",
      insight: "A cross-encoder scores a query against a candidate directly and finds relationships a similarity search cannot. It is also too expensive to run over the whole corpus — which is why it lands in post-retrieval: embeddings fetch a shortlist, the cross-encoder reorders it, and only the top N survive." },
  ],
  references: [
    { order: 1, stage: "START HERE", title: 'LLM Engineers Handbook — Ch.4 "RAG Feature Pipeline"', url: null, inLibrary: true, byline: null,
      teaches: "How embeddings are produced and used in a real pipeline — model choice, cosine similarity, chunking, pre- and post-retrieval.",
      addsOverPrevious: "the foundation" },
    { order: 2, stage: "NEXT →", title: "NV-Retriever: Improving text embedding models with effective hard-negative mining", url: "https://arxiv.org/html/2407.15831v1", inLibrary: false, byline: "NVIDIA, 2024",
      teaches: "Why the negatives you train against decide embedding quality — and the trap that on MS-MARCO about 70% of the passages most similar to a query deserve a positive label (Qu et al., 2020).",
      addsOverPrevious: "the single highest-leverage choice in training" },
    { order: 3, stage: "THEN →", title: "Recent Advances in Text Embedding: A Review of Top-Performing Methods on MTEB", url: "https://arxiv.org/html/2406.01607v1", inLibrary: false, byline: null,
      teaches: "What the leading models actually do — multi-stage contrastive training, hard-negative mining, instruction tuning, cross-encoder distillation — and the 8 tasks MTEB scores them on.",
      addsOverPrevious: "the recipe behind the leaderboard" },
    { order: 4, stage: "DEEP DIVE →", title: "Matryoshka Representation Learning", url: "https://arxiv.org/abs/2205.13147", inLibrary: false, byline: "Kusupati et al., 2022",
      teaches: "Training one embedding that can be truncated: 14x smaller vectors at comparable ImageNet-1K accuracy, with no retraining. (Reported on vision — do not carry the number straight to text.)",
      addsOverPrevious: "the storage-cost dimension the others ignore" },
  ],
},
{
  node: "AdversarialEvaluation",
  title: "Adversarial Evaluation",
  overview: [
    "Adversarial evaluation measures how a system holds up under inputs built to break it. It is the measuring half of a pair: red teaming searches adaptively for new failure modes, and adversarial evaluation scores a system against a fixed set of them.",
    "**Why it matters:** ordinary evaluation reports performance on inputs that behave. What takes a deployed system down is the input that does not — the jailbreak, the injection, the malformed query nobody anticipated. Those are a different measurement problem with a different failure mode.",
    "**The shape of the work:** generate adversarial cases, run them as a repeatable suite, score with a judge, and then ask the uncomfortable question about the score itself — whether it means what you think, and whether it can be compared to anyone else's.",
  ].join("\n\n"),
  cherries: [
    { axis: "Generating the inputs nobody planned for",
      chunk: "019e785e-8a3c-7630-96ee-04ff1edd4bb4", primary: true,
      insight: "Red teaming increasingly uses language models to build synthetic datasets that deliberately do not match what developers expect — anomalous patterns, noisy inputs, biased distributions, out-of-domain examples. Malformed queries that imitate real user error stress the system beyond individual prompts, and the whole thing can be automated and re-run." },
    { axis: "Where automation stops",
      chunk: "019e785e-8a34-7280-94b9-0c84533cb700",
      insight: "Automated tools generate adversarial prompts and test thousands of variations at scale, which is the only way to get coverage. The book is direct about the limit: human creativity remains irreplaceable for the nuanced vulnerabilities the tools miss. The two are complements, not stages." },
    { axis: "Where evaluation belongs in the lifecycle",
      chunk: "019e785e-8a32-7cbb-ba5f-1afc2abc24d3",
      insight: "Evaluation moved from a phase at the end to a trigger on every merge and every model update. Keeping one consistent source of truth for metrics over time is what makes regressions visible early — and automated evaluation still does not tell the whole story, so effective teams sample outputs for human review alongside it." },
    { axis: "What an evaluation case has to contain",
      chunk: "019e785e-8a3c-7386-a41d-723501c7d2f8",
      insight: "A usable evaluation case pins down both the input state and the expected outcome — the order, the conversation so far, and the exact tool call plus the phrases the reply must contain. Without the expected side written out, validation cannot be automated and the suite degrades into a demo." },
    { axis: "Why LLM evaluation is not ML evaluation",
      chunk: "019e785e-8a3e-7335-9e53-7f87c5be32c2",
      insight: "Three differences, stated plainly: a single numerical metric rarely fits, because one model does many tasks; feature engineering largely disappears, since the model takes raw text; and interpretability is gone — you cannot read off why the answer came out that way, only ask the model to explain itself." },
    { axis: "Measuring the cost of the failure, not just its rate",
      chunk: "019e785e-8a28-76d1-ae5c-2e57e85aa72c",
      insight: "Hallucination work has moved toward hybrid human-AI loops with experts correcting output before it propagates, and toward cost-aware evaluation — frameworks that quantify a \"hallucination cost\" by weighing accuracy gains against the compute spent to get them. Reducing the error rate is not automatically worth what it costs." },
  ],
  references: [
    { order: 1, stage: "START HERE", title: 'Building Applications with AI Agents — Ch.12 "Protecting Agentic Systems"', url: null, inLibrary: true, byline: "Michael Albada",
      teaches: "The threat vectors, the defensive techniques, and red teaming as a repeatable cycle rather than a one-off exercise.",
      addsOverPrevious: "the foundation" },
    { order: 2, stage: "NEXT →", title: 'LLM Engineers Handbook — Ch.7 "Evaluating LLMs"', url: null, inLibrary: true, byline: null,
      teaches: "How LLM evaluation differs from ML evaluation, and how general, domain-specific and task-specific evaluations divide the work.",
      addsOverPrevious: "the measurement side" },
    { order: 3, stage: "THEN →", title: "HarmBench: A Standardized Evaluation Framework for Automated Red Teaming", url: "https://arxiv.org/html/2402.04249v2", inLibrary: false, byline: "Mazeika et al., 2024",
      teaches: "18 red teaming methods against 33 LLMs over 510 harmful behaviours — and the finding that within model families robustness shows no correlation with model size.",
      addsOverPrevious: "numbers you can compare, and one result that surprises" },
    { order: 4, stage: "DEEP DIVE →", title: "Comparison requires valid measurement: Rethinking attack success rate comparisons in AI red teaming", url: "https://arxiv.org/html/2601.18076v1", inLibrary: false, byline: "Chouldechova, Cooper et al.",
      teaches: "Why most published ASR comparisons do not support their conclusions — incompatible estimands, and judges whose true positive rates differ across the systems being compared.",
      addsOverPrevious: "it takes back the confidence the previous three gave you" },
  ],
},
];
